#!/bin/sh
# /etc/init.d/pipeline2d
# Bert Frees <bertfrees@gmail.com>
#
### BEGIN INIT INFO
# Provides:          pipeline2
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the DAISY Pipeline 2 server
# Description:       Start and stop the DAISY Pipeline 2 server.
### END INIT INFO

set -e

. /lib/lsb/init-functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=pipeline2d
DESC="DAISY Pipeline 2 server"
SCRIPTNAME=/etc/init.d/$NAME
DAEMON=${pipeline.home}/bin/pipeline2
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid

if [ `id -u` -ne 0 ]; then
	echo "$SCRIPTNAME must be run as root"
	exit 1
fi

test -x $DAEMON || (echo "$DAEMON is not installed" && exit 0)

case "$1" in
	start)
		if [ -e $PIDFILE ]; then
			status_of_proc -p $PIDFILE $DAEMON $NAME >/dev/null && status="0" || status="$?"
			if [ $status = "0" ]; then
				exit
			fi
		fi
		log_daemon_msg "starting $DESC"
		if start-stop-daemon --make-pidfile --pidfile $PIDFILE --start --background --quiet --oknodo \
			--exec $DAEMON -- $DAEMON_ARGS; then
			sleep 5
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	stop)
		if [ -e $PIDFILE ]; then
			status_of_proc -p $PIDFILE $DAEMON $NAME >/dev/null && status="0" || status="$?"
			if [ $status = "0" ]; then
				log_daemon_msg "stopping $DESC"
				if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
					/bin/rm -rf $PIDFILE
					sleep 5
					log_end_msg 0
				else
					log_end_msg 1
				fi
			fi
		else
			log_end_msg 0
		fi
		;;
	restart)
		$0 stop && sleep 2 && $0 start
		;;
	status)
		status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
		;;
	*)
		log_action_msg "Usage: $SCRIPTNAME {start|stop|restart|status}"
		exit 1
esac

exit 0
